create table harvest_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  weight_grams float8 not null,
  crop_type text not null,
  image_path text
);
